# Generated by Django 4.1.7 on 2023-03-23 19:27

import apps.foro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=apps.foro.models.upload_post_image
            ),
        ),
    ]
