# Generated by Django 4.1.7 on 2023-03-23 19:28

import apps.foro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foro", "0002_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="", upload_to=apps.foro.models.upload_post_image
            ),
            preserve_default=False,
        ),
    ]
