# Generated by Django 4.1.7 on 2023-03-24 21:08

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foro", "0004_alter_comment_body_alter_post_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="updated"),
        ),
        migrations.AlterField(
            model_name="subreddit",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
