# Generated by Django 4.1.7 on 2023-03-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foro", "0005_alter_post_body_alter_subreddit_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subreddit",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
